In [1]:
import numpy as np

arr1 = np.array ([10,20,30,40,50])

In [3]:
print ("Array: ")
print (arr1)

print ("\nShape : ",arr1.shape)
print("Dimensions: ", arr1.ndim )
print("Data Type :", arr1.dtype)
print ("Size" , arr1.size)
print ("Item Size: ", arr1.itemsize)

Array: 
[10 20 30 40 50]

Shape :  (5,)
Dimensions:  1
Data Type : int64
Size 5
Item Size:  8


In [5]:
#indexing and slicing
print( "first element :" ,arr1[0] )
print( "last element :", arr1[-1]  )
print(   "slice :" , arr1[1:4])

#reshaping
matrix =np.arrange(1,13).reshape(3,4)
print(matrix)

print("Rows:", matrix.shape[0])
print("Columns:", matrix.shape[1])

first element : 10
last element : 50
slice : [20 30 40]


AttributeError: module 'numpy' has no attribute 'arrange'

In [6]:
#indexing and slicing
print( "first element :" ,arr1[0] )
print( "last element :", arr1[-1]  )
print(   "slice :" , arr1[1:4])

#reshaping
matrix =np.arange(1,13).reshape(3,4)
print(matrix)

print("Rows:", matrix.shape[0])
print("Columns:", matrix.shape[1])

first element : 10
last element : 50
slice : [20 30 40]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Rows: 3
Columns: 4


In [7]:
#statistical operations

data = np.array([25, 30, 35, 40, 45])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Maximum:", np.max(data))
print("Minimum:", np.min(data))

Mean: 35.0
Median: 35.0
Standard Deviation: 7.0710678118654755
Maximum: 45
Minimum: 25


In [8]:
#vectorized operations
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Square:", a ** 2)

Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]
Square: [ 1  4  9 16]


In [9]:
#random data
np.random.seed(42)

random_data = np.random.randint(1, 100, size=10)

print(random_data)

[52 93 15 72 61 21 83 87 75 75]


In [11]:
#filtering data
scores = np.array([45, 78, 88, 92, 56, 39, 95])

passed = scores[scores >= 60]

print("Passed Students:")
print(passed)

Passed Students:
[78 88 92 95]


In [10]:
study_hours = np.array([1, 2, 3, 4, 5, 6])
marks = np.array([35, 45, 50, 60, 70, 85])

correlation = np.corrcoef(study_hours, marks)

print(correlation)

[[1.        0.9894757]
 [0.9894757 1.       ]]


In [13]:
#mini data analysis
import numpy as np

np.random.seed(42)

study_hours = np.random.randint(1, 11, 50)

marks = 30 + study_hours * 6 + np.random.randint(-10, 10, 50)

print("Study Hours:", study_hours)
print("Marks:", marks)

print("Average Study Hours:", np.mean(study_hours))
print("Average Marks:", np.mean(marks))

correlation = np.corrcoef(study_hours, marks)
print("Correlation:")
print(correlation)

Study Hours: [ 7  4  8  5  7 10  3  7  8  5  4  8  8  3  6  5  2  8  6  2  5  1 10  6
  9  1 10  3  7  4  9  3  5  3  7  5  9  7  2  4  9  2 10  9 10  5  2  4
  7  8]
Marks: [76 46 81 66 65 97 45 65 69 55 53 71 85 49 57 59 35 81 71 46 57 39 87 71
 86 43 94 50 70 58 86 38 56 46 62 61 81 72 50 60 81 34 82 74 84 59 38 52
 68 76]
Average Study Hours: 5.84
Average Marks: 63.74
Correlation:
[[1.        0.9472771]
 [0.9472771 1.       ]]
